server:
  port: 8091

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb?TimeZone=UTC

    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  admin:
    email: admin@atelier.dev
    password: admin123456
    firstName: Store
    lastName: Admin

management:
  endpoints:
    web:
      exposure:
        include: health,info