server:
  port: 8098

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5440/reviewdb?TimeZone=UTC
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
